source 'https://rubygems.org'

gem 'RedCloth'

platform :jruby do
  gem 'therubyrhino'
end

platform :ruby do
  gem 'therubyracer'
end

#
# test
#
group :development, :test do
  gem 'spring'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-given'
  gem 'pry'
  gem 'simplecov', require: false
end

# helpers
gem 'awesome_print'
gem 'dotenv-rails'
gem 'dotenv-deployment'

