source 'https://rubygems.org'

group :test, :development do
  gem 'simplecov', :require => false, :group => :test
  #gem 'awesome_print'
  gem 'prettyprint'
  gem 'rspec'
  gem 'rspec-given'
  gem 'interactive_editor'
end
